"""add conversation title

Revision ID: 262dd0044a4a
Revises: 644092713aa1
Create Date: 2026-06-11 20:51:30.652897+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262dd0044a4a'
down_revision: Union[str, Sequence[str], None] = '644092713aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('title', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'title')
    # ### end Alembic commands ###
