"""add user_account table

Revision ID: 644092713aa1
Revises: cf1b77f77520
Create Date: 2026-06-11 20:10:21.586830+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644092713aa1'
down_revision: Union[str, Sequence[str], None] = 'cf1b77f77520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_api_key_hash'), 'user_account', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_api_key_hash'), table_name='user_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###
