apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-service
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
