name: opensearch
services:
  opensearch:
    container_name: os-container
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
    networks:
      - os-net
    ports:
      - 9200:9200
    volumes:
      - ./opendata:/usr/share/opensearch/data
  dashboard:
    container_name: osd-container
    image: opensearchproject/opensearch-dashboards:latest
    environment:
      - OPENSEARCH_HOSTS=http://os-container:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true # Important but hard-to-find command
    networks:
      - os-net
    depends_on:
      - opensearch
    ports:
      - 5601:5601
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 30s
networks:
  os-net:
    driver: bridge