from datetime import datetime, timezone

from sqlalchemy.orm import DeclarativeBase, MappedAsDataclass


class Base(DeclarativeBase, MappedAsDataclass):
    """Base declarative class for SQLAlchemy.

    Uses a Dataclass mixin to allow us to use additional functionality, like `default_factory`.
    """

    pass


def current_utc() -> datetime:
    """Return the current datetime in UTC.

    Used as a default factory and onupdate callable for timestamp columns.
    """
    return datetime.now(timezone.utc)


# Conversation / message models land here in the next step; the first
# autogenerated migration picks them up via ``Base.metadata``.
